---
- hosts: osx_target

  tasks:
  - name: Enable ARD Screen Sharing through SSH.
    raw: "/System/Library/CoreServices/RemoteManagement/\ 
         ARDAgent.app/Contents/Resources/kickstart -activate\ 
         - configure -access -on -users admin -privs -all\
         -restart -agent -menu"
